eureka:
  client:
    serviceUrl:
      defaultZone: https://peer1:8070/eureka/,http://peer2:8074/eureka/,http://peer3:8075/eureka/

---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8070
eureka:
  instance:
    hostname: peer1

---
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8074
eureka:
  instance:
    hostname: peer2

---
spring:
  config:
    activate:
      on-profile: peer3
server:
  port: 8075
eureka:
  instance:
    hostname: peer3
