eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekaserver1:8070/eureka/,http://eurekaserver2:8074/eureka/,http://eurekaserver3:8075/eureka/

---
spring:
  config:
    activate:
      on-profile: eurekaserver1
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver1

---
spring:
  config:
    activate:
      on-profile: eurekaserver2
server:
  port: 8074
eureka:
  instance:
    hostname: eurekaserver2

---
spring:
  config:
    activate:
      on-profile: eurekaserver3
server:
  port: 8075
eureka:
  instance:
    hostname: eurekaserver3
