spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8074
eureka:
  instance:
    hostname: eurekaserver2
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eurekaserver3:8075/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
