spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver1
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eurekaserver2:8074/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
